version: "3"

services:
  prod-app:
    container_name: prod-app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: node main
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - prod-postgres
    networks:
      - app-network
    restart: always
    environment:
      - DB_HOST=prod-postgres
    env_file:
      - .env
  prod-postgres:
    container_name: prod-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./prod-db/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge